### ISSUE TITLE
Set Scrollbar Height

### ISSUE THREAD

**Issue by grommett** [thomd/jquery-scroll#2]
Is there anyway to set the scrollbar container height? That would be a very nice option.

**Comment by thomd** [comment]
I've added an option "handleHeight" which allows to set an explicit handle height. Default is a handleHeight set to 'auto' which calculates a proportional height.

See the examples in demo.html for an implementation.

Is this what you imagined?

**Comment by grommett** [comment]
Yes this is exactly what I had imagined. Thanks, so much!
