### ISSUE TITLE
Programmatic Positioning

### ISSUE THREAD

**Issue by supersighs** [thomd/jquery-scroll#4]
Is it possible to set the scroll pane to a certain position programmatically? For example:

```
    var s = $('.scrollable').scrollbar({
        handleHeight: 151,
        arrows: false
    });

   s.scrollTo(500)
```

**Comment by supersighs** [comment]
Or even passing in a scrollTop parameter on instantiation:
    $('.scrollable').scrollbar({
        handleHeight: 151,
        arrows: false,
        scrollTop:500
    });

**Comment by thomd** [comment]
hi tomaski, this is not possible, though I find this a nice idea. Guess I will add this, but I prefer your first example.

**Comment by supersighs** [comment]
I've forked and implemented the second option. I'm not sure if it is the approach you would have taken, but it worked for what I was trying to accomplish.

**Comment by thomd** [comment]
I like it
