### ISSUE TITLE
Slow mousewheel scrolling

### ISSUE THREAD

**Issue by computron5000** [thomd/jquery-scroll#8]
Hi, 

First off, great plugin! 

My only issue with it is slow mousewheel scrolling.
Is there anything I can adjust to speed things up?

Thanks!

J

**Comment by ludal** [comment]
Hi, 

I fixed this issue by changing this line: 

 // Old school scrollwheel delta
        if(event.wheelDelta){
            delta = event.wheelDelta /120;
        }

change "120" by "10" or whatever you want. 

Ludo

**Comment by computron5000** [comment]
That worked perfectly.

Thanks Ludo!
